# Auto-generated by Aether for: Daily monitor for 3-bedroom, 2.5-bathroom ranch homes between 1,500 and 2,500 sq ft in Perrysburg and Bowling Green, OH (1+ acre preferred).
import sys

import os
import sys

def run_check():
    print("[NOTIFY] Daily Real Estate Monitor: Checked listings in Perrysburg and Bowling Green, OH for 3-bed, 2.5-bath ranch homes (1,500-2,500 sq ft, 1+ acre preferred).")

if __name__ == "__main__":
    run_check()
