import os
import re
import time
import subprocess
from typing import Dict, Any, Optional

DOSSIER_DIR = os.path.join("data", "dossiers")
LATEST_DOSSIER_LINK = os.path.join("data", "scratchpad", "latest_dossier.md")

def _sanitize_filename(name: str) -> str:
    """Cleans a string for safe use as a Windows/POSIX filename."""
    cleaned = re.sub(r'[\\/*?:"<>| ]', "_", name.strip())
    return cleaned[:64].strip("_")

def export_research_dossier(
    title: str,
    content_markdown: str,
    category: str = "research",
    open_immediately: bool = False
) -> Dict[str, Any]:
    """
    Saves a comprehensive, structured Markdown dossier or report to disk.
    Use this tool whenever you gather detailed research, family trees, public records, 
    or multi-step analysis that is too lengthy to speak entirely aloud.
    
    Args:
        title: Short descriptive title for the document (e.g., 'Stanley_Orlop_Genealogy')
        content_markdown: Full structured Markdown content with headers, bullet points, and tables.
        category: Sub-category ('genealogy', 'technical', 'system_audit', 'general')
        open_immediately: Whether to pop the saved file open in the default system viewer.
    """
    os.makedirs(DOSSIER_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(LATEST_DOSSIER_LINK), exist_ok=True)

    date_str = time.strftime("%Y%m%d_%H%M%S")
    safe_title = _sanitize_filename(title)
    filename = f"{date_str}_{safe_title}.md"
    file_path = os.path.join(DOSSIER_DIR, filename)

    # Format document header
    header = f"""# {title}
*Generated by Aether Desktop Agent • {time.strftime('%Y-%m-%d %H:%M:%S')}*
*Category: {category}*

---

"""
    full_content = header + content_markdown.strip() + "\n"

    try:
        # Write permanent timestamped dossier
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(full_content)

        # Write or overwrite scratchpad pointer
        with open(LATEST_DOSSIER_LINK, "w", encoding="utf-8") as f:
            f.write(full_content)

        # Optional open in default editor
        if open_immediately:
            try:
                os.startfile(file_path)
            except Exception as launch_err:
                print(f"[WARN] [DOSSIER] Could not auto-open file: {launch_err}")

        print(f"[INFO] [DOSSIER] Successfully exported research dossier to {file_path}")
        return {
            "status": "success",
            "file_path": os.path.abspath(file_path),
            "filename": filename,
            "char_count": len(full_content),
            "directive": (
                "File written successfully. Deliver a concise 2-3 sentence verbal summary of the "
                "findings over voice and mention that the complete details have been saved to the dossier."
            )
        }
    except Exception as e:
        print(f"[ERROR] [DOSSIER] Failed to write research dossier: {e}")
        return {
            "status": "error",
            "message": str(e)
        }
